events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 4173;

        location / {
            root /app/dist;
            index index.html;
            try_files $uri $uri/ /index.html;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
        }
    }
}
